apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-deployment
  namespace: argocd-namespace
spec:
  project: default
  source:
    repoURL: https://github.com/Mikeyifr/Mongo_FastAPI.git
    path: charts/appchart
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins-deployment
  namespace: argocd-namespace
spec:
  project: default
  source:
    repoURL: https://github.com/Mikeyifr/Mongo_FastAPI.git
    path: charts/jenkinschart
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: jenkins-namespace
  syncPolicy:
    automated:
      selfHeal: true
