apiVersion: v1
kind: Service
metadata:
  name: jenkins-master
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.jenkinsMaster.service.type }}
  ports:
    - port: {{ .Values.jenkinsMaster.service.port }}
      targetPort: 8080
      nodePort: {{ .Values.jenkinsMaster.service.nodePort }}
  selector:
    app: jenkins-master

---
