# service account
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "jenkinschart.serviceAccountName" . }}
  namespace: jenkins-namespace
  labels:
    {{- include "jenkinschart.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
---
# role creation
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: jenkins-namespace
  name: jenkins-secrets-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "watch"]
---
# role binding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-agent-rolebinding
  namespace: jenkins-namespace
subjects:
- kind: ServiceAccount
  name: jenkins-sa
  namespace: jenkins-namespace
roleRef:
  kind: Role
  name: jenkins-secrets-reader
  apiGroup: rbac.authorization.k8s.io