FROM alpine:3.14
RUN apk add --update python3 py3-pip
RUN pip install --upgrade pip
RUN pip install fastapi
RUN pip install uvicorn
RUN pip install jinja2
RUN pip install python-multipart
RUN pip install pymongo
WORKDIR /app
COPY . /app
EXPOSE 8000
CMD ["uvicorn", "router:app", "--host", "0.0.0.0", "--port", "8000"]
